network:
  ip: localhost
  port: 8080
file:
  directory: "./files" # Updatable files directory path
  exclude: "a^" # Ignore all files matched by this regex
  recursive: true # Is the file indexing in depth ?
  chunk-size: 8192 # The data chunk size in bytes. A bigger size will increase memory speed but it will also increase memory footprint.
  compression-blacklist:
    - "mpeg"
    - "jpeg"
    - "png"
    - "gif"
    - "pdf"
    - "mp3"
    - "avi"
    - "ogg"
    - "mp4"
    - "jar"